/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { JournalEntryService } from "../journalEntry.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { JournalEntryCreateInput } from "./JournalEntryCreateInput";
import { JournalEntry } from "./JournalEntry";
import { JournalEntryFindManyArgs } from "./JournalEntryFindManyArgs";
import { JournalEntryWhereUniqueInput } from "./JournalEntryWhereUniqueInput";
import { JournalEntryUpdateInput } from "./JournalEntryUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class JournalEntryControllerBase {
  constructor(
    protected readonly service: JournalEntryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: JournalEntry })
  @nestAccessControl.UseRoles({
    resource: "JournalEntry",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createJournalEntry(
    @common.Body() data: JournalEntryCreateInput
  ): Promise<JournalEntry> {
    return await this.service.createJournalEntry({
      data: data,
      select: {
        content: true,
        createdAt: true,
        id: true,
        isPublic: true,
        tags: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [JournalEntry] })
  @ApiNestedQuery(JournalEntryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "JournalEntry",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async journalEntries(
    @common.Req() request: Request
  ): Promise<JournalEntry[]> {
    const args = plainToClass(JournalEntryFindManyArgs, request.query);
    return this.service.journalEntries({
      ...args,
      select: {
        content: true,
        createdAt: true,
        id: true,
        isPublic: true,
        tags: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: JournalEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JournalEntry",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async journalEntry(
    @common.Param() params: JournalEntryWhereUniqueInput
  ): Promise<JournalEntry | null> {
    const result = await this.service.journalEntry({
      where: params,
      select: {
        content: true,
        createdAt: true,
        id: true,
        isPublic: true,
        tags: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: JournalEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JournalEntry",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateJournalEntry(
    @common.Param() params: JournalEntryWhereUniqueInput,
    @common.Body() data: JournalEntryUpdateInput
  ): Promise<JournalEntry | null> {
    try {
      return await this.service.updateJournalEntry({
        where: params,
        data: data,
        select: {
          content: true,
          createdAt: true,
          id: true,
          isPublic: true,
          tags: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: JournalEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JournalEntry",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteJournalEntry(
    @common.Param() params: JournalEntryWhereUniqueInput
  ): Promise<JournalEntry | null> {
    try {
      return await this.service.deleteJournalEntry({
        where: params,
        select: {
          content: true,
          createdAt: true,
          id: true,
          isPublic: true,
          tags: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
