/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { StreakService } from "../streak.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StreakCreateInput } from "./StreakCreateInput";
import { Streak } from "./Streak";
import { StreakFindManyArgs } from "./StreakFindManyArgs";
import { StreakWhereUniqueInput } from "./StreakWhereUniqueInput";
import { StreakUpdateInput } from "./StreakUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class StreakControllerBase {
  constructor(
    protected readonly service: StreakService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Streak })
  @nestAccessControl.UseRoles({
    resource: "Streak",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createStreak(@common.Body() data: StreakCreateInput): Promise<Streak> {
    return await this.service.createStreak({
      data: data,
      select: {
        createdAt: true,
        currentStreak: true,
        id: true,
        longestStreak: true,
        milestones: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Streak] })
  @ApiNestedQuery(StreakFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Streak",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async streaks(@common.Req() request: Request): Promise<Streak[]> {
    const args = plainToClass(StreakFindManyArgs, request.query);
    return this.service.streaks({
      ...args,
      select: {
        createdAt: true,
        currentStreak: true,
        id: true,
        longestStreak: true,
        milestones: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Streak })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Streak",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async streak(
    @common.Param() params: StreakWhereUniqueInput
  ): Promise<Streak | null> {
    const result = await this.service.streak({
      where: params,
      select: {
        createdAt: true,
        currentStreak: true,
        id: true,
        longestStreak: true,
        milestones: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Streak })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Streak",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateStreak(
    @common.Param() params: StreakWhereUniqueInput,
    @common.Body() data: StreakUpdateInput
  ): Promise<Streak | null> {
    try {
      return await this.service.updateStreak({
        where: params,
        data: data,
        select: {
          createdAt: true,
          currentStreak: true,
          id: true,
          longestStreak: true,
          milestones: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Streak })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Streak",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteStreak(
    @common.Param() params: StreakWhereUniqueInput
  ): Promise<Streak | null> {
    try {
      return await this.service.deleteStreak({
        where: params,
        select: {
          createdAt: true,
          currentStreak: true,
          id: true,
          longestStreak: true,
          milestones: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
