/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HabitService } from "../habit.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HabitCreateInput } from "./HabitCreateInput";
import { Habit } from "./Habit";
import { HabitFindManyArgs } from "./HabitFindManyArgs";
import { HabitWhereUniqueInput } from "./HabitWhereUniqueInput";
import { HabitUpdateInput } from "./HabitUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HabitControllerBase {
  constructor(
    protected readonly service: HabitService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Habit })
  @nestAccessControl.UseRoles({
    resource: "Habit",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHabit(@common.Body() data: HabitCreateInput): Promise<Habit> {
    return await this.service.createHabit({
      data: data,
      select: {
        completionDates: true,
        createdAt: true,
        description: true,
        goalFrequency: true,
        id: true,
        name: true,
        progress: true,
        reminders: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Habit] })
  @ApiNestedQuery(HabitFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Habit",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async habits(@common.Req() request: Request): Promise<Habit[]> {
    const args = plainToClass(HabitFindManyArgs, request.query);
    return this.service.habits({
      ...args,
      select: {
        completionDates: true,
        createdAt: true,
        description: true,
        goalFrequency: true,
        id: true,
        name: true,
        progress: true,
        reminders: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Habit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Habit",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async habit(
    @common.Param() params: HabitWhereUniqueInput
  ): Promise<Habit | null> {
    const result = await this.service.habit({
      where: params,
      select: {
        completionDates: true,
        createdAt: true,
        description: true,
        goalFrequency: true,
        id: true,
        name: true,
        progress: true,
        reminders: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Habit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Habit",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHabit(
    @common.Param() params: HabitWhereUniqueInput,
    @common.Body() data: HabitUpdateInput
  ): Promise<Habit | null> {
    try {
      return await this.service.updateHabit({
        where: params,
        data: data,
        select: {
          completionDates: true,
          createdAt: true,
          description: true,
          goalFrequency: true,
          id: true,
          name: true,
          progress: true,
          reminders: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Habit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Habit",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHabit(
    @common.Param() params: HabitWhereUniqueInput
  ): Promise<Habit | null> {
    try {
      return await this.service.deleteHabit({
        where: params,
        select: {
          completionDates: true,
          createdAt: true,
          description: true,
          goalFrequency: true,
          id: true,
          name: true,
          progress: true,
          reminders: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
